client_config_backend: settings
client_config:
  client_id: 1069695483567-mvci5o9pvq1kpe5r0oc7d2un144a3jft.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file